services:
  backend2:
    build:
      context: ./backends
      dockerfile: Dockerfile.backend
    environment:
    - PORT=9002
  backend3:
    build:
      context: ./backends
      dockerfile: Dockerfile.backend
    environment:
    - PORT=9003
  load-balancer:
    build: .
    depends_on:
    - backend2
    - backend3
    ports:
    - 8080:8080
    volumes:
    - ./config:/root/config
version: '3.8'
